#!/usr/bin/env bash
# vi:syntax=sh

echo "updating all git submodules"

git submodule update --recursive --remote

exists () {
  type "$1" >/dev/null 2>/dev/null
}

dieIfNotExists () {
    if $(exists "$1"); then
        echo "$1 exists"
    else
        echo "$1 does not exist"
        exit 1
    fi;
}

echo "----------------"
echo ""
echo "checking that all requirements are available"

dieIfNotExists node
dieIfNotExists npm
dieIfNotExists meteor

echo "requirements passed"
echo ""
echo "----------------"
echo ""

for D in *; do
  if [ -d "${D}" ]; then
    if [ "$D" = "node_modules" ]; then
    else
      echo ""
      echo "----------------"
      echo ""
      echo "${D} -- installing dependencies"
      cd "$D" && npm install
      echo "${D} -- dependencies installed"
      echo ""
      cd ..
    fi
  fi
done

echo "everything installed"
